// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmyUZEmuN8fkFZTxGm_3NCFMrSEU2hcuY',
    appId: '1:723214011157:web:91d72a1ee0bb017099371c',
    messagingSenderId: '723214011157',
    projectId: 'pomac-shuwier-dev',
    authDomain: 'pomac-shuwier-dev.firebaseapp.com',
    storageBucket: 'pomac-shuwier-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqE_vYp8Nn1MpMLl_mks7iHodzEuPBFX4',
    appId: '1:723214011157:android:ed09b227f4a6192899371c',
    messagingSenderId: '723214011157',
    projectId: 'pomac-shuwier-dev',
    storageBucket: 'pomac-shuwier-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjb9ftmcCSoXIfH5g5Un3ZXoQl1UDe0dY',
    appId: '1:723214011157:ios:6724059ee8c7df8799371c',
    messagingSenderId: '723214011157',
    projectId: 'pomac-shuwier-dev',
    storageBucket: 'pomac-shuwier-dev.firebasestorage.app',
    iosBundleId: 'com.pomac.feed',
  );
}
